config/routes.rb
MyAddress::Engine.routes.draw do

  root "myhome#index"

  resources :addresses
  resources :streets
  resources :townships
  resources :cities
  resources :states
  resources :nationalities
  resources :countries
  
  namespace :api do
    get 'lookup/country'
    get 'lookup/state'
    get 'lookup/city'
    get 'lookup/township'
    get 'lookup/street'
  end
  
end

app/models/my_address/address.rb
module MyAddress
  class Address < ActiveRecord::Base
    belongs_to :street
    belongs_to :township
  end
end

app/models/my_address/city.rb
module MyAddress
  class City < ActiveRecord::Base
    belongs_to :state
    has_many :townships
    
    def self.autocomplete_lookup(state_id, query, locale)
      if locale
        result = City.select(:id, :name, :locale_name, :code).where("lower(locale_name) like lower('%#{query}%') and state_id = #{state_id}").order("locale_name asc")
      
      else
        result = City.select(:id, :name, :locale_name, :code).where("lower(name) like lower('%#{query}%') and state_id = #{state_id}").order("name asc")
        
      end
    end
    
    def self.import_seed_data
       cities_json = JSON.parse(File.read("db/seeds/cities.json"));

       #Delete all previous records
       City.delete_all
     
       cities_json.each do |city|
         #puts state
         state = State.find_by_code(city["state_code"])
       
         c = City.new(:name => city["name"], :state => state, :locale_name => city["locale_name"], :code => city["code"])
         c.save
         
         puts "#{c.name} city added into db"
       end
    end
  end
end

app/models/my_address/country.rb
module MyAddress
  class Country < ActiveRecord::Base
    
    def self.autocomplete_lookup(query, locale)
      if locale
        result = Country.select(:id, :name, :locale_name, :cca2).where("lower(locale_name) like lower('%#{query}%')").order("locale_name asc")
      
      else
        result = Country.select(:id, :name, :locale_name, :cca2).where("lower(name) like lower('%#{query}%')").order("name asc")
        
      end
    end
    
    def self.import_seed_data
       countries_json = JSON.parse(File.read("db/seeds/countries.json"));

       #Delete all previous records
       Country.delete_all
     
       countries_json.each do |country|
                 c = Country.new(country)
                 c.save
                 puts "#{c.name} country added to db."
       end
    end
  end
end

app/models/my_address/nationality.rb
module MyAddress
  class Nationality < ActiveRecord::Base
    belongs_to :country
    
    def self.autocomplete_lookup(query, locale)
      if locale
        result = Nationality.select(:id, :name, :locale_name, :code).where("lower(locale_name) like lower('%#{query}%')").order("locale_name asc")
      
      else
        result = Nationality.select(:id, :name, :locale_name, :code).where("lower(name) like lower('%#{query}%')").order("name asc")
        
      end
    end
    
    def self.import_seed_data
      nationality = File.read("db/seeds/nationalities.csv")
      nationalities = nationality.split(",")
    
      Nationality.delete_all
    
      nationalities.each do |nation|
        n = Nationality.new
        n.name = nation
        n.locale_name = nation
        n.save
        
        puts "#{n.name} nationality added to db!"
      end
    
    end
  end
end

app/models/my_address/state.rb
module MyAddress
  class State < ActiveRecord::Base
    belongs_to :country
    has_many :cities
    
    def self.autocomplete_lookup(country_id, query, locale)
      if locale
        result = State.select(:id, :name, :locale_name, :code).where("lower(locale_name) like lower('%#{query}%') and country_id = #{country_id}").order("locale_name asc")
      
      else
        result = State.select(:id, :name, :locale_name, :code).where("lower(name) like lower('%#{query}%') and country_id = #{country_id}").order("name asc")
        
      end
    end
    
    def self.import_seed_data
       states_json = JSON.parse(File.read("db/seeds/states.json"));

       #Delete all previous records
       State.delete_all
     
       states_json.each do |state|
         #puts state
         country = Country.find_by_cca2(state["country_iso"])
       
         s = State.new(:name => state["name"], :country => country, :locale_name => state["locale_name"], :code => state["code"])
         s.save
         puts "#{s.name} state added into database"
       end
    end
    
  end
end

app/models/my_address/street.rb
module MyAddress
  class Street < ActiveRecord::Base
    belongs_to :township
    
    def self.autocomplete_lookup(township_id, query, locale)
      if locale
        result = Street.select(:id, :name).where("lower(locale_name) like lower('%#{query}%') and township_id = #{township_id}").order("locale_name asc")
      
      else
        result = Street.select(:id, :name).where("lower(name) like lower('%#{query}%') and township_id = #{township_id}").order("name asc")
        
      end
    end
    
    def self.import_seed_data
       streets_json = JSON.parse(File.read("db/seeds/streets.json"));
     
     
       #Delete all previous records
       Street.delete_all
     
       streets_json.each do |street|
         #puts state
         township = Township.find_by_code(street["township_code"])
       
         s = Street.new(:name => street["name"], :township_id => township.id , :locale_name => street["locale_name"])
         s.save
         
         puts "#{s.name} street name added to db!"
       end
    end
  end
end

app/controllers/my_address/addresses_controller.rb
require_dependency "my_address/application_controller"

module MyAddress
  class AddressesController < ApplicationController
    before_action :set_address, only: [:show, :edit, :update, :destroy]

    # GET /addresses
    def index
      @addresses = Address.all
    end

    # GET /addresses/1
    def show
    end

    # GET /addresses/new
    def new
      @address = Address.new
    end

    # GET /addresses/1/edit
    def edit
    end

    # POST /addresses
    def create
      @address = Address.new(address_params)

      if @address.save
        redirect_to @address, notice: 'Address was successfully created.'
      else
        render :new
      end
    end

    # PATCH/PUT /addresses/1
    def update
      if @address.update(address_params)
        redirect_to @address, notice: 'Address was successfully updated.'
      else
        render :edit
      end
    end

    # DELETE /addresses/1
    def destroy
      @address.destroy
      redirect_to addresses_url, notice: 'Address was successfully destroyed.'
    end

    private
      # Use callbacks to share common setup or constraints between actions.
      def set_address
        @address = Address.find(params[:id])
      end

      # Only allow a trusted parameter "white list" through.
      def address_params
        params.require(:address).permit(:number, :building_name, :street_name, :street_id, :township_id)
      end
  end
end

app/controllers/my_address/api/lookup_controller.rb
require_dependency "my_address/application_controller"

module MyAddress
  class Api::LookupController < ApplicationController
    def country
      @countries = Country.all.order("name asc")
    end

    def state
      @states = State.all.order("name asc")
    end

    def city
      @cities = City.all.order("name asc")
      
      # respond_to do |format|
 #        format.html
 #        format.json { render json: @cities}
 #      end
    end

    def township
      @townships = Township.all.order("name asc")
    end

    def street
      @streets = Street.all.order("name asc")
    end
  end
end

app/controllers/my_address/application_controller.rb
module MyAddress
  class ApplicationController < ActionController::Base
  end
end

app/controllers/my_address/cities_controller.rb
require_dependency "my_address/application_controller"

module MyAddress
  class CitiesController < ApplicationController
    before_action :set_city, only: [:show, :edit, :update, :destroy]

    # GET /cities
    def index
      @cities = City.all
    end

    # GET /cities/1
    def show
    end

    # GET /cities/new
    def new
      @city = City.new
    end

    # GET /cities/1/edit
    def edit
    end

    # POST /cities
    def create
      @city = City.new(city_params)

      if @city.save
        redirect_to @city, notice: 'City was successfully created.'
      else
        render :new
      end
    end

    # PATCH/PUT /cities/1
    def update
      if @city.update(city_params)
        redirect_to @city, notice: 'City was successfully updated.'
      else
        render :edit
      end
    end

    # DELETE /cities/1
    def destroy
      @city.destroy
      redirect_to cities_url, notice: 'City was successfully destroyed.'
    end

    private
      # Use callbacks to share common setup or constraints between actions.
      def set_city
        @city = City.find(params[:id])
      end

      # Only allow a trusted parameter "white list" through.
      def city_params
        params.require(:city).permit(:name, :locale_name, :state_id, :code)
      end
  end
end

app/controllers/my_address/countries_controller.rb
require_dependency "my_address/application_controller"

module MyAddress
  class CountriesController < ApplicationController
    before_action :set_country, only: [:show, :edit, :update, :destroy]

    # GET /countries
    def index
      @countries = Country.all
    end

    # GET /countries/1
    def show
    end

    # GET /countries/new
    def new
      @country = Country.new
    end

    # GET /countries/1/edit
    def edit
    end

    # POST /countries
    def create
      @country = Country.new(country_params)

      if @country.save
        redirect_to @country, notice: 'Country was successfully created.'
      else
        render :new
      end
    end

    # PATCH/PUT /countries/1
    def update
      if @country.update(country_params)
        redirect_to @country, notice: 'Country was successfully updated.'
      else
        render :edit
      end
    end

    # DELETE /countries/1
    def destroy
      @country.destroy
      redirect_to countries_url, notice: 'Country was successfully destroyed.'
    end

    private
      # Use callbacks to share common setup or constraints between actions.
      def set_country
        @country = Country.find(params[:id])
      end

      # Only allow a trusted parameter "white list" through.
      def country_params
        params.require(:country).permit(:name, :locale_name, :cca2, :ccn3, :cca3, :tld, :currency, :calling_code, :capital, :alt_spellings, :relevance, :region, :subregion)
      end
  end
end

app/controllers/my_address/myhome_controller.rb
require_dependency "my_address/application_controller"

module MyAddress
  class MyhomeController < ApplicationController
    def index
    end
  end
end

app/controllers/my_address/nationalities_controller.rb
require_dependency "my_address/application_controller"

module MyAddress
  class NationalitiesController < ApplicationController
    before_action :set_nationality, only: [:show, :edit, :update, :destroy]

    # GET /nationalities
    def index
      @nationalities = Nationality.all
    end

    # GET /nationalities/1
    def show
    end

    # GET /nationalities/new
    def new
      @nationality = Nationality.new
    end

    # GET /nationalities/1/edit
    def edit
    end

    # POST /nationalities
    def create
      @nationality = Nationality.new(nationality_params)

      if @nationality.save
        redirect_to @nationality, notice: 'Nationality was successfully created.'
      else
        render :new
      end
    end

    # PATCH/PUT /nationalities/1
    def update
      if @nationality.update(nationality_params)
        redirect_to @nationality, notice: 'Nationality was successfully updated.'
      else
        render :edit
      end
    end

    # DELETE /nationalities/1
    def destroy
      @nationality.destroy
      redirect_to nationalities_url, notice: 'Nationality was successfully destroyed.'
    end

    private
      # Use callbacks to share common setup or constraints between actions.
      def set_nationality
        @nationality = Nationality.find(params[:id])
      end

      # Only allow a trusted parameter "white list" through.
      def nationality_params
        params.require(:nationality).permit(:country_id, :name, :locale_name, :code)
      end
  end
end

app/controllers/my_address/states_controller.rb
require_dependency "my_address/application_controller"

module MyAddress
  class StatesController < ApplicationController
    before_action :set_state, only: [:show, :edit, :update, :destroy]

    # GET /states
    def index
      @states = State.all
    end

    # GET /states/1
    def show
    end

    # GET /states/new
    def new
      @state = State.new
    end

    # GET /states/1/edit
    def edit
    end

    # POST /states
    def create
      @state = State.new(state_params)

      if @state.save
        redirect_to @state, notice: 'State was successfully created.'
      else
        render :new
      end
    end

    # PATCH/PUT /states/1
    def update
      if @state.update(state_params)
        redirect_to @state, notice: 'State was successfully updated.'
      else
        render :edit
      end
    end

    # DELETE /states/1
    def destroy
      @state.destroy
      redirect_to states_url, notice: 'State was successfully destroyed.'
    end

    private
      # Use callbacks to share common setup or constraints between actions.
      def set_state
        @state = State.find(params[:id])
      end

      # Only allow a trusted parameter "white list" through.
      def state_params
        params.require(:state).permit(:name, :locale_name, :country_id, :code)
      end
  end
end

app/controllers/my_address/streets_controller.rb
require_dependency "my_address/application_controller"

module MyAddress
  class StreetsController < ApplicationController
    before_action :set_street, only: [:show, :edit, :update, :destroy]

    # GET /streets
    def index
      @streets = Street.all
    end

    # GET /streets/1
    def show
    end

    # GET /streets/new
    def new
      @street = Street.new
    end

    # GET /streets/1/edit
    def edit
    end

    # POST /streets
    def create
      @street = Street.new(street_params)

      if @street.save
        redirect_to @street, notice: 'Street was successfully created.'
      else
        render :new
      end
    end

    # PATCH/PUT /streets/1
    def update
      if @street.update(street_params)
        redirect_to @street, notice: 'Street was successfully updated.'
      else
        render :edit
      end
    end

    # DELETE /streets/1
    def destroy
      @street.destroy
      redirect_to streets_url, notice: 'Street was successfully destroyed.'
    end

    private
      # Use callbacks to share common setup or constraints between actions.
      def set_street
        @street = Street.find(params[:id])
      end

      # Only allow a trusted parameter "white list" through.
      def street_params
        params.require(:street).permit(:name, :locale_name, :township_id)
      end
  end
end

app/controllers/my_address/townships_controller.rb
require_dependency "my_address/application_controller"

module MyAddress
  class TownshipsController < ApplicationController
    before_action :set_township, only: [:show, :edit, :update, :destroy]

    # GET /townships
    def index
      @townships = Township.all
    end

    # GET /townships/1
    def show
    end

    # GET /townships/new
    def new
      @township = Township.new
    end

    # GET /townships/1/edit
    def edit
    end

    # POST /townships
    def create
      @township = Township.new(township_params)

      if @township.save
        redirect_to @township, notice: 'Township was successfully created.'
      else
        render :new
      end
    end

    # PATCH/PUT /townships/1
    def update
      if @township.update(township_params)
        redirect_to @township, notice: 'Township was successfully updated.'
      else
        render :edit
      end
    end

    # DELETE /townships/1
    def destroy
      @township.destroy
      redirect_to townships_url, notice: 'Township was successfully destroyed.'
    end

    private
      # Use callbacks to share common setup or constraints between actions.
      def set_township
        @township = Township.find(params[:id])
      end

      # Only allow a trusted parameter "white list" through.
      def township_params
        params.require(:township).permit(:name, :locale_name, :city_id, :code)
      end
  end
end

app/helpers/my_address/addresses_helper.rb
module MyAddress
  module AddressesHelper
  end
end

app/helpers/my_address/api/lookup_helper.rb
module MyAddress
  module Api::LookupHelper
  end
end

app/helpers/my_address/application_helper.rb
module MyAddress
  module ApplicationHelper
  end
end

app/views/my_address/countries/_form.html.erb
<%= form_for(@country) do |f| %>
  <% if @country.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@country.errors.count, "error") %> prohibited this country from being saved:</h2>

      <ul>
      <% @country.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :locale_name %><br>
    <%= f.text_field :locale_name %>
  </div>
  <div class="field">
    <%= f.label :cca2 %><br>
    <%= f.text_field :cca2 %>
  </div>
  <div class="field">
    <%= f.label :ccn3 %><br>
    <%= f.text_field :ccn3 %>
  </div>
  <div class="field">
    <%= f.label :cca3 %><br>
    <%= f.text_field :cca3 %>
  </div>
  <div class="field">
    <%= f.label :tld %><br>
    <%= f.text_field :tld %>
  </div>
  <div class="field">
    <%= f.label :currency %><br>
    <%= f.text_field :currency %>
  </div>
  <div class="field">
    <%= f.label :calling_code %><br>
    <%= f.text_field :calling_code %>
  </div>
  <div class="field">
    <%= f.label :capital %><br>
    <%= f.text_field :capital %>
  </div>
  <div class="field">
    <%= f.label :alt_spellings %><br>
    <%= f.text_field :alt_spellings %>
  </div>
  <div class="field">
    <%= f.label :relevance %><br>
    <%= f.text_field :relevance %>
  </div>
  <div class="field">
    <%= f.label :region %><br>
    <%= f.text_field :region %>
  </div>
  <div class="field">
    <%= f.label :subregion %><br>
    <%= f.text_field :subregion %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/my_address/countries/edit.html.erb
<h1>Editing country</h1>

<%= render 'form' %>

<%= link_to 'Show', @country %> |
<%= link_to 'Back', countries_path %>

app/views/my_address/countries/index.html.erb
<h1>Listing countries</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Locale name</th>
      <th>Cca2</th>
      <th>Ccn3</th>
      <th>Cca3</th>
      <th>Tld</th>
      <th>Currency</th>
      <th>Calling code</th>
      <th>Capital</th>
      <th>Alt spellings</th>
      <th>Relevance</th>
      <th>Region</th>
      <th>Subregion</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @countries.each do |country| %>
      <tr>
        <td><%= country.name %></td>
        <td><%= country.locale_name %></td>
        <td><%= country.cca2 %></td>
        <td><%= country.ccn3 %></td>
        <td><%= country.cca3 %></td>
        <td><%= country.tld %></td>
        <td><%= country.currency %></td>
        <td><%= country.calling_code %></td>
        <td><%= country.capital %></td>
        <td><%= country.alt_spellings %></td>
        <td><%= country.relevance %></td>
        <td><%= country.region %></td>
        <td><%= country.subregion %></td>
        <td><%= link_to 'Show', country %></td>
        <td><%= link_to 'Edit', edit_country_path(country) %></td>
        <td><%= link_to 'Destroy', country, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Country', new_country_path %>

app/views/my_address/countries/new.html.erb
<h1>New country</h1>

<%= render 'form' %>

<%= link_to 'Back', countries_path %>

app/views/my_address/countries/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @country.name %>
</p>

<p>
  <strong>Locale name:</strong>
  <%= @country.locale_name %>
</p>

<p>
  <strong>Cca2:</strong>
  <%= @country.cca2 %>
</p>

<p>
  <strong>Ccn3:</strong>
  <%= @country.ccn3 %>
</p>

<p>
  <strong>Cca3:</strong>
  <%= @country.cca3 %>
</p>

<p>
  <strong>Tld:</strong>
  <%= @country.tld %>
</p>

<p>
  <strong>Currency:</strong>
  <%= @country.currency %>
</p>

<p>
  <strong>Calling code:</strong>
  <%= @country.calling_code %>
</p>

<p>
  <strong>Capital:</strong>
  <%= @country.capital %>
</p>

<p>
  <strong>Alt spellings:</strong>
  <%= @country.alt_spellings %>
</p>

<p>
  <strong>Relevance:</strong>
  <%= @country.relevance %>
</p>

<p>
  <strong>Region:</strong>
  <%= @country.region %>
</p>

<p>
  <strong>Subregion:</strong>
  <%= @country.subregion %>
</p>

<%= link_to 'Edit', edit_country_path(@country) %> |
<%= link_to 'Back', countries_path %>